### PR TITLE
config mode color for cisco

### PR DESCRIPTION
**Pull request by Raizo62**
- add 2 colortables : "hostname" and "configmode"
- redefine in cm_cisco.ini the labels "common_prompt_priv" and "common_prompt_nonpriv" to have a color for the hostname and another color for the config mode

The aim is to have a color to distinguish the config mode in cisco.

### CODE REVIEW

**Comment by Raizo62** [comment]
You know your code better than me.

My clicol runs on system with limited ressources.
I suppose that : 
- if i create a  cisco_prompt_priv, i have 2 regular expression which are calculated (common_prompt_priv for nothing)
- if i use again common_prompt_priv, i have 1 regular expression which is calculated

**Comment by realvitya** [comment]
I didn't mean to offense. I was curious. So the way these rules are read is that they are sorted by priority. If you want your rules to take precedence over the common ones then I see two approach:
1. If the new rule is more granular from the existing one, you can lower priority. Once the rule is matched and the option is BREAK(default), no other rules will be used. If your rule is not containing backtracking or other expensive regex idioms, then you are good and don't waste too much resource in case it's not matching.
2. Don't merge that but use custom colormap. Put those in ~/.clicol/clicol_customcmap.ini with the same name you want to override. Like you did with this merge.

**Comment by Raizo62** [comment]
Don't worry, i am not offence. I need/ask your advice.

I will try your fist approach.

**Comment by realvitya** [comment]
@Raizo62, I tested this patch:
(venv-3.5) vkertesz@ubuntu:~/clicol/clicol/ini$ clicol-test "common_prompt|cisco_prompt"
My problem is twofold. First, that prompt is a bit too colorful. Even for me :)
Secondly, cisco_prompt is not more granular but rather the same text matches. You can see that cisco_prompt is now colors the common_prompt rule example text.
I think we need to  decide what we want. Cisco has no special "cisco-only" prompt. That looks similar to linux prompt or other network device prompt I've seen. If you just don't like common_prompt, I'd suggest to use the 2nd approach I mentioned up there and simply override common_prompt rule match and replace.

**Comment by Raizo62** [comment]
> My problem is twofold. First, that prompt is a bit too colorful. Even for me :)

it's a matter of habit ;-)

> Secondly, cisco_prompt is not more granular but rather the same text matches. You can see that cisco_prompt is now colors the common_prompt rule example text.

As teacher, i see that my students do 3 errors : 
- They tape command on the bad console : they must see the name of the device (Router1)
- They forget to become admin : they must see that they are admin ( # ) or guest ( > )
- They forget that config commands must be do in "config mode" 

> Cisco has no special "cisco-only" prompt. 

I never used juniper, but i didn't see a config mode in the prompt with this device (perhaps :RE:0%  ?)

> That looks similar to linux prompt 

Linux doesn't have this config mode. And my Linux prompt tries to distinguish admin and user account.

> or other network device prompt I've seen.

Perhaps....

**Comment by realvitya** [comment]
@Raizo62, I did a voting at my company amongst my colleagues. They all voted for no :(
I understand it would help for the students who are beginners but for everyone we feel it would be too much.
Here is my suggestion:
Put your changes to `clicol_customcmap.ini` and `clicol_customct.ini` in your cfgdir folder (defaulted to _~/.clicol_, but can be specified with `--cfg` argument) and override/add your rules there! I tested it this way. So I can't merge this change, but you can use it freely in your environment!

**Comment by Raizo62** [comment]
> @Raizo62, I did a voting at my company amongst my colleagues. They all voted for no :(

It's a matter of habit ;-)
People don't like the changing
They should have tested it for a week before they decided

>I understand it would help for the students who are beginners but for everyone we feel it would be too much.

I am not a beginner in Linux/Cisco, and these colors in my linux prompt is very useful. It should be the same with cisco, because it highlights information useful to expert.

> Here is my suggestion:
> Put your changes to clicol_customcmap.ini and clicol_customct.ini in your cfgdir folder (defaulted to ~/.clicol)

I did this. It works
Sorry for you, you will not use it  ;-)

**Comment by realvitya** [comment]
@Raizo62 did you try the plugins? Especially the [extra](https://github.com/realvitya/clicol_plugin_extra) one?

**Comment by Raizo62** [comment]
> @Raizo62 did you try the plugins? Especially the extra one?

Yes, i am testing it

A idea for the commit : you can keep the functionality but change the default colors to have the same color with hostname, the config mode, and the admin mode. You will see as before, but anybody else will can have the same as me

**Comment by realvitya** [comment]
Ok, but in that case, please remove cisco specific pattern and edit the common prompts instead!
What if you set the colors the same in the global rules and override it for yourself? Is it a good compromise? :)

**Comment by Raizo62** [comment]
> Ok, but in that case, please remove cisco specific pattern and edit the common prompts instead!

I don't understand why you ask that. I use the Cisco pattern to identify the hostname, the admin mode ( > or # ) and the characters in the config mode ( between bracket ( ) ). It is specific to Cisco.
The pattern of a prompt of another system will be different. It is not common.

> What if you set the colors the same in the global rules and override it for yourself? Is it a good compromise? :)

I have tested but it is not work : i forgot the hosthome color. With your system, the hosthome will have 2 colors (admin/guest), and i have 1 label.
Or i must add in colortable a label for hosthomepriv and hosthomenonpriv. It's not intuitive.

It's too bad.
I stay with changes in my cfgdir folder

**Comment by realvitya** [comment]
I leave this idea in my mind though...

**Pull request closed without merging**
